### ISSUE TITLE
TODO 전부 해결하기

### ISSUE THREAD

**Issue by minding2796** [Team-QSS/KonoPuro-Unity#134]
### Work

- [ ] #132 
- [ ] #133 
- [ ] Tiers 이미지 로드
- [ ] 설정창 저장 할지 말지 물어보는 패널 띄우기
- [ ] 실험용 삭제필요
- [ ] 빌드시에 포함 고려 (커서가 화면 밖으로 안나가는 기능)
- [ ] 플로우 진행 중 상호작용 불가 or 턴이 아님 표시
- [ ] 능력 사용 유형에 따라 선택할 카드를 지정
- [ ] 시간이 모자람 공지
- [ ] #105 
- [ ] 승패 연출
- [ ] 덱이 형식에 맞지 않을 때 적용 안됨 표시
- [ ] 카드들 정렬하기

### Additional

![image](https://github.com/user-attachments/assets/7626c69b-af78-4b65-800c-326a359a8b39)
